name: Build and Push to Quay.io


on:
 pull_request:
   branches:
     - main
 workflow_run:
   workflows:
     - Java CI # Asegura que este flujo corra después del flujo "Java CI"
   types:
     - completed


jobs:
 build-and-push:
   runs-on: ubuntu-latest


   steps:
     # 1. Checkout the repository
     - name: Checkout code
       uses: actions/checkout@v3


     # 2. Get commit date
     - name: Get commit date
       id: get-date
       run: echo "commit_date=$(date -u +'%Y%m%d')" >> $GITHUB_ENV


     # 3. Log in to Quay.io
     - name: Log in to Quay.io
       uses: docker/login-action@v2
       with:
         registry: quay.io
         username: ${{ secrets.QUAY_USERNAME }}
         password: ${{ secrets.QUAY_PASSWORD }}


     # 4. Build the Docker image
     - name: Build Docker image
       run: |
         docker build -f src/main/docker/Dockerfile.jvm -t quay.io/${{ secrets.QUAY_USERNAME }}/api-hello-wworld:${{ env.commit_date }}_${{ github.short_sha }} .


     # 5. Push the Docker image to Quay.io
     - name: Push Docker image
       run: |
         docker push quay.io/${{ secrets.QUAY_USERNAME }}/api-hello-wworld:${{ env.commit_date }}_${{ github.short_sha }}