name: Java CI

on:
  push:
    branches:
      - develop # Cambia "main" por el nombre de tu rama principal, si es diferente.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Usar Temurin JDK
          java-version: '17'      # Cambia según la versión de Java que uses

      # 3. Instalar dependencias y ejecutar pruebas
      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
