name: Java CI

on:
  push:
    branches:
      - develop # Change "main" to your main branch name if it's different.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin JDK
          java-version: '17'      # Change to the Java version you're using

      # 3. Install dependencies
      - name: Build with Maven
        run: mvn clean install

      # 4. Run tests
      - name: Run tests on develop
        if: github.ref == 'refs/heads/develop'  # Only runs on the 'develop' branch
        run: mvn test -Dtest=**/*Test.java  # Run only tests ending with 'Test.java'

      - name: Run all tests on main
        if: github.ref == 'refs/heads/main'  # Only runs on the 'main' branch
        run: mvn test  # Run all tests
