name: Java CI - Push

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Install dependencies
      - name: Build with Maven
        run: mvn clean install

      # 4. Run unit tests for other branches
      - name: Run unit tests for other branches
        if: github.event_name == 'push' &&  !(github.base_ref == 'main' || github.base_ref == 'develop')
        run: mvn test -Dtest=**/*Test.java
