name: E2E Test on OpenShift

on:
  workflow_run:
    workflows:
      - Deploy to OpenShift
    types:
      - completed

jobs:
  e2e-test:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar la URL de la aplicación desde el artifact
      - name: Download Application URL
        uses: actions/download-artifact@v4
        with:
          name: app-url

      - name: Load Application URL
        run: |
          APP_URL=$(cat app-url.txt)
          echo "APP_URL=$APP_URL" >> $GITHUB_ENV
        shell: bash

      # 2. Instalar dependencias para realizar test HTTP
      - name: Install HTTP Client
        run: |
          sudo apt update
          sudo apt install -y curl jq

      # 3. Esperar a que la aplicación esté lista antes de probarla
      - name: Wait for Application to be Ready
        run: |
          MAX_RETRIES=10
          RETRY_DELAY=5  # Segundos
          COUNT=0

          while [[ $COUNT -lt $MAX_RETRIES ]]; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/hello")
            if [[ "$RESPONSE" == "200" ]]; then
              echo "Application is ready!"
              exit 0
            fi
            echo "Waiting for application... Attempt $((COUNT+1))"
            sleep $RETRY_DELAY
            COUNT=$((COUNT+1))
          done

          echo "Application did not become ready in time."
          exit 1

      # 4. Ejecutar Test de Integración
      - name: Run E2E Test
        run: |
          RESPONSE=$(curl -s $APP_URL/hello)
          echo "Response: $RESPONSE"
          if [[ "$RESPONSE" != "Hello world" ]]; then
            echo "Test failed: Expected 'Hello world' but got '$RESPONSE'"
            exit 1
          fi
          echo "Test passed!"
